SYSCALL0 (OS_GETPID, sys_getpid)
SYSCALL0 (OS_GETPPID, sys_getppid)
SYSCALL3R(OS_WRITE, sys_write, int, const void *, size_t)
SYSCALL3R(OS_READ, sys_read, int, void *, size_t)
SYSCALL0R(OS_FORK, sys_fork)
SYSCALL1 (OS_EXIT, sys_exit, int)
SYSCALL3 (OS_OPEN, sys_open, const char *, int, mode_t)
SYSCALL1 (OS_CLOSE, sys_close, int)
SYSCALL3 (OS_LSEEK, sys_lseek, int, off_t, int)
SYSCALL3 (OS_GETDENTS, sys_getdents, int, struct dirent *, size_t)
SYSCALL1 (OS_DUP, sys_dup, int)
SYSCALL2 (OS_DUP2, sys_dup2, int, int)
SYSCALL1 (OS_BRK, sys_brk, uintptr_t)
SYSCALL1 (OS_UNLINK, sys_unlink, const char *)
SYSCALL1 (OS_RMDIR, sys_rmdir, const char *)
SYSCALL2 (OS_MKDIR, sys_mkdir, const char *, mode_t)
SYSCALL3R(OS_EXECVE, sys_execve, const char *, char * const *, char * const *)
SYSCALL3R(OS_WAITPID, sys_waitpid, pid_t, int *, int)
SYSCALL2 (OS_GETCWD, sys_getcwd, char *, size_t)
SYSCALL1 (OS_CHDIR, sys_chdir, const char *)
SYSCALL2 (OS_STAT, sys_stat, const char *, struct stat *)
SYSCALL2 (OS_LSTAT, sys_lstat, const char *, struct stat *)
SYSCALL2 (OS_FSTAT, sys_fstat, int, struct stat *)
SYSCALL2 (OS_CLOCK_GETTIME, sys_clock_gettime, int, struct timespec *)
SYSCALL2R(OS_NANOSLEEP, sys_nanosleep, const struct timespec *, struct timespec *)
SYSCALL2 (OS_SETPGID, sys_setpgid, pid_t, pid_t)
SYSCALL0 (OS_GETPGRP, sys_getpgrp)
SYSCALL2 (OS_KILL, sys_kill, pid_t, int)
SYSCALL1 (OS_UNAME, sys_uname, struct utsname *)
SYSCALL3 (OS_IOCTL, sys_ioctl, int, int, void *)
SYSCALL1 (OS_MMAP, sys_mmap, struct os_mmap_request *)
SYSCALL3 (OS_FCNTL, sys_fcntl, int, int, int)
SYSCALL4 (OS_PTHREAD_CREATE, sys_pthread_create, pthread_t * , const pthread_attr_t * , void *, void *)
SYSCALL2R(OS_PTHREAD_JOIN, sys_pthread_join, pthread_t, void **)
SYSCALL3 (OS_SIGACTION, sys_sigaction, int, const struct sigaction *, struct sigaction *)
SYSCALL2 (OS_GETITIMER, sys_getitimer, int, struct itimerval *)
SYSCALL3 (OS_SETITIMER, sys_setitimer, int, const struct itimerval *, struct itimerval *)
SYSCALL5R(OS_SELECT, sys_select, int, fd_set *, fd_set *, fd_set *, struct timeval *)
SYSCALL1 (OS_PIPE, sys_pipe, int *)
SYSCALL2 (OS_SYSLOG, sys_syslog, int, const char *)
SYSCALL2 (OS_UTIME, sys_utime, const char *, const struct utimbuf *)
SYSCALL2 (OS_RENAME, sys_rename, const char *, const char *)
SYSCALL0R(OS_PAUSE, sys_pause)
SYSCALL1R(OS_ALARM, sys_alarm, unsigned)
SYSCALL2 (OS_GETMNTINFO, sys_getmntinfo, struct statvfs *, int)
SYSCALL3 (OS_READLINK, sys_readlink, const char *, char *, size_t)
SYSCALL2 (OS_SYMLINK, sys_symlink, const char *, const char *)
SYSCALL2 (OS_LINK, sys_link, const char *, const char *)
SYSCALL2 (OS_FTRUNCATE, sys_ftruncate, int, off_t)
SYSCALL4 (OS_FSTATAT, sys_fstatat, int, const char *, struct stat *, int)
SYSCALL1 (OS_FCHDIR, sys_fchdir, int)
SYSCALL1 (OS_GETPGID, sys_getpgid, pid_t)
SYSCALL3 (OS_SOCKET, sys_socket, int, int, int)
SYSCALL3 (OS_BIND, sys_bind, int, const struct sockaddr *, socklen_t)
SYSCALL3R(OS_ACCEPT, sys_accept, int, struct sockaddr *, socklen_t *)
SYSCALL3 (OS_CONNECT, sys_connect, int, const struct sockaddr *, socklen_t)
SYSCALL2 (OS_LISTEN, sys_listen, int, int)
SYSCALL2 (OS_CHMOD, sys_chmod, const char *, mode_t)
